INSERT INTO	Rubro	(	Codigo	,	Nombre	,	Descripcion	)	VALUES	(	1	,	Administración 	,	null	)	;
INSERT INTO	Rubro	(	Codigo	,	Nombre	,	Descripcion	)	VALUES	(	2	,	Costos operativos 	,	null	)	;
INSERT INTO	Rubro	(	Codigo	,	Nombre	,	Descripcion	)	VALUES	(	3	,	Documentación 	,	null	)	;
INSERT INTO	Rubro	(	Codigo	,	Nombre	,	Descripcion	)	VALUES	(	4	,	Equipos	,	null	)	;
INSERT INTO	Rubro	(	Codigo	,	Nombre	,	Descripcion	)	VALUES	(	5	,	Honorarios investigadores externos 	,	null	)	;
INSERT INTO	Rubro	(	Codigo	,	Nombre	,	Descripcion	)	VALUES	(	6	,	Imprevistos	,	null	)	;
INSERT INTO	Rubro	(	Codigo	,	Nombre	,	Descripcion	)	VALUES	(	7	,	Material bibliográfico	,	null	)	;
INSERT INTO	Rubro	(	Codigo	,	Nombre	,	Descripcion	)	VALUES	(	8	,	Material de difusión y promoción de resultados	,	null	)	;
INSERT INTO	Rubro	(	Codigo	,	Nombre	,	Descripcion	)	VALUES	(	9	,	Materiales 	,	null	)	;
INSERT INTO	Rubro	(	Codigo	,	Nombre	,	Descripcion	)	VALUES	(	10	,	Materiales e insumos 	,	null	)	;
INSERT INTO	Rubro	(	Codigo	,	Nombre	,	Descripcion	)	VALUES	(	11	,	Monitores  (estudiantes Icesi )	,	null	)	;
INSERT INTO	Rubro	(	Codigo	,	Nombre	,	Descripcion	)	VALUES	(	12	,	Participación en misiones tecnológicas 	,	null	)	;
INSERT INTO	Rubro	(	Codigo	,	Nombre	,	Descripcion	)	VALUES	(	13	,	Personal Cientifico	,	null	)	;
INSERT INTO	Rubro	(	Codigo	,	Nombre	,	Descripcion	)	VALUES	(	14	,	Personal de Apoyo	,	null	)	;
INSERT INTO	Rubro	(	Codigo	,	Nombre	,	Descripcion	)	VALUES	(	15	,	Personal H.C.	,	null	)	;
INSERT INTO	Rubro	(	Codigo	,	Nombre	,	Descripcion	)	VALUES	(	16	,	Publicaciones y patentes	,	null	)	;
INSERT INTO	Rubro	(	Codigo	,	Nombre	,	Descripcion	)	VALUES	(	17	,	Salidas de campo	,	null	)	;
INSERT INTO	Rubro	(	Codigo	,	Nombre	,	Descripcion	)	VALUES	(	18	,	Seminarios y cursos 	,	null	)	;
INSERT INTO	Rubro	(	Codigo	,	Nombre	,	Descripcion	)	VALUES	(	19	,	Servicios técnicos	,	null	)	;
INSERT INTO	Rubro	(	Codigo	,	Nombre	,	Descripcion	)	VALUES	(	20	,	Servicios tecnológicos 	,	null	)	;
INSERT INTO	Rubro	(	Codigo	,	Nombre	,	Descripcion	)	VALUES	(	21	,	Software	,	null	)	;
INSERT INTO	Rubro	(	Codigo	,	Nombre	,	Descripcion	)	VALUES	(	22	,	Socialización de la Investigación	,	null	)	;
