INSERT INTO	Producto	(	Codigo	,	Subtipo	,	Tipo	)	VALUES	(	A	,	ARTICULO 	,	NC	)	;
INSERT INTO	Producto	(	Codigo	,	Subtipo	,	Tipo	)	VALUES	(	L	,	LIBRO	,	NC	)	;
INSERT INTO	Producto	(	Codigo	,	Subtipo	,	Tipo	)	VALUES	(	CL	,	CAPITULO DE LIBRO	,	NC	)	;
INSERT INTO	Producto	(	Codigo	,	Subtipo	,	Tipo	)	VALUES	(	P	,	PATENTE	,	NC	)	;
INSERT INTO	Producto	(	Codigo	,	Subtipo	,	Tipo	)	VALUES	(	VV	,	VARIEDAD VEGETAL	,	NC	)	;
INSERT INTO	Producto	(	Codigo	,	Subtipo	,	Tipo	)	VALUES	(	VV	,	VARIEDAD ANIMAL	,	NC	)	;
INSERT INTO	Producto	(	Codigo	,	Subtipo	,	Tipo	)	VALUES	(	DI	,	DISEÑO INDUSTRIAL	,	DTI	)	;
INSERT INTO	Producto	(	Codigo	,	Subtipo	,	Tipo	)	VALUES	(	EC	,	ESQUEMA DE CIRCUITO INTEGRADO	,	DTI	)	;
INSERT INTO	Producto	(	Codigo	,	Subtipo	,	Tipo	)	VALUES	(	SW	,	SOFTWARE	,	DTI	)	;
INSERT INTO	Producto	(	Codigo	,	Subtipo	,	Tipo	)	VALUES	(	PP	,	PLANTA PILOTO	,	DTI	)	;
INSERT INTO	Producto	(	Codigo	,	Subtipo	,	Tipo	)	VALUES	(	PI	,	PROTOTIPO INDUSTRIAL	,	DTI	)	;
INSERT INTO	Producto	(	Codigo	,	Subtipo	,	Tipo	)	VALUES	(	SE	,	SECRETO EMPRESARIAL	,	DTI	)	;
INSERT INTO	Producto	(	Codigo	,	Subtipo	,	Tipo	)	VALUES	(	EBT	,	EMPRESA DE BASE TECNOLÓGICA CREADAS (SPINN- OFF UNIVERSITARIOS Y EMPRESARIALES)	,	DTI	)	;
INSERT INTO	Producto	(	Codigo	,	Subtipo	,	Tipo	)	VALUES	(	IG	,	INNOOVACIÓN GENERADA EN LA GESTIÓN EMPRESARIAL	,	DTI	)	;
INSERT INTO	Producto	(	Codigo	,	Subtipo	,	Tipo	)	VALUES	(	IP	,	INNOVACIÓN EN PROCEDIMEINTO	,	DTI	)	;
INSERT INTO	Producto	(	Codigo	,	Subtipo	,	Tipo	)	VALUES	(	RN	,	REGULACIONES, NORMAS, REGLAMENTOS O LEGISLACIONES	,	DTI	)	;
INSERT INTO	Producto	(	Codigo	,	Subtipo	,	Tipo	)	VALUES	(	CC	,	CONSULTORÍA CIENTÍFICO-TECNOLÓGICA E INFORME TÉCNICO	,	DTI	)	;
INSERT INTO	Producto	(	Codigo	,	Subtipo	,	Tipo	)	VALUES	(	PC	,	PARTICIPACIÓN CIUDADANA EN PROYECTOS DE CTI	,	ASC	)	;
INSERT INTO	Producto	(	Codigo	,	Subtipo	,	Tipo	)	VALUES	(	EPC	,	ESPACIOS DE PARTICIAPCIÓN CIUDADANA EN CTI	,	ASC	)	;
INSERT INTO	Producto	(	Codigo	,	Subtipo	,	Tipo	)	VALUES	(	EPF	,	ESTRATEGIAS PEDAGÓGICAS PARA EL FOMENTO A LA CTI	,	ASC	)	;
INSERT INTO	Producto	(	Codigo	,	Subtipo	,	Tipo	)	VALUES	(	ECC	,	ESTRATEGIAS DE COMUNICACIÓN DEL CONOCIMIENTO	,	ASC	)	;
INSERT INTO	Producto	(	Codigo	,	Subtipo	,	Tipo	)	VALUES	(	GC	,	GENERACIÓN DE CONTENIDOS	,	ASC	)	;
INSERT INTO	Producto	(	Codigo	,	Subtipo	,	Tipo	)	VALUES	(	EC	,	EVENTO CIENTÍFICO	,	ASC	)	;
INSERT INTO	Producto	(	Codigo	,	Subtipo	,	Tipo	)	VALUES	(	RCE	,	RED DE CONOCIMIENTO ESPECIALIZADO	,	ASC	)	;
INSERT INTO	Producto	(	Codigo	,	Subtipo	,	Tipo	)	VALUES	(	DT	,	DOCUMENTO DE TRABAJO (WORKING PAPER)	,	ASC	)	;
INSERT INTO	Producto	(	Codigo	,	Subtipo	,	Tipo	)	VALUES	(	BDR	,	BOLETÍN DIVULGATIVO DE RESULTADO DE INVESTIGACIÓN	,	ASC	)	;
INSERT INTO	Producto	(	Codigo	,	Subtipo	,	Tipo	)	VALUES	(	ERC	,	EDICIÓN DE REVISTA CIENTIFICA O DE LIBRO RESULTADO DE INVESTIGACIÓN	,	ASC	)	;
INSERT INTO	Producto	(	Codigo	,	Subtipo	,	Tipo	)	VALUES	(	IFI	,	INFORME FINAL DE INVESTIGACIÓN	,	ASC	)	;
INSERT INTO	Producto	(	Codigo	,	Subtipo	,	Tipo	)	VALUES	(	R	,	RECONOCIMIENTOS	,	ASC	)	;
INSERT INTO	Producto	(	Codigo	,	Subtipo	,	Tipo	)	VALUES	(	TD	,	TESIS DE DOCTORADO	,	FRH	)	;
INSERT INTO	Producto	(	Codigo	,	Subtipo	,	Tipo	)	VALUES	(	TM	,	TRABAJO DE GRADO DE MAESTRÍA	,	FRH	)	;
INSERT INTO	Producto	(	Codigo	,	Subtipo	,	Tipo	)	VALUES	(	TP	,	TRABAJO DE GRADO PREGRADO	,	FRH	)	;
INSERT INTO	Producto	(	Codigo	,	Subtipo	,	Tipo	)	VALUES	(	PID	,	PROYECTO DE INVESTIGACIÓN Y DESARROLLO	,	FRH	)	;
INSERT INTO	Producto	(	Codigo	,	Subtipo	,	Tipo	)	VALUES	(	PF	,	PROYECTO ID+I CON FORMACIÓN	,	FRH	)	;
INSERT INTO	Producto	(	Codigo	,	Subtipo	,	Tipo	)	VALUES	(	F	,	PROYECTO ID+I CON FORMACIÓN	,	FRH	)	;
INSERT INTO	Producto	(	Codigo	,	Subtipo	,	Tipo	)	VALUES	(	PE	,	PROYECTO DE EXTENSIÓN Y RESPONSABILIDAD SOCIAL EN CTI	,	FRH	)	;
INSERT INTO	Producto	(	Codigo	,	Subtipo	,	Tipo	)	VALUES	(	ACF	,	APOYO A PROGRAMA O CURSO DE FORMACIÓN DE INVESTIGADORES	,	FRH	)	;
INSERT INTO	Producto	(	Codigo	,	Subtipo	,	Tipo	)	VALUES	(	A	,	APOYO A PROGRAMA O CURSO DE FORMACIÓN DE INVESTIGADORES	,	FRH	)	;
INSERT INTO	Producto	(	Codigo	,	Subtipo	,	Tipo	)	VALUES	(	AAL	,	ACOMPAÑAMIENTO Y ASESORÍA DE LÍNEA TEMÁTICA DEL PROGRAMA ONDAS	,	FRH	)	;
